In [3]:
import pandas as pd
df = pd.read_csv("/Users/arnavangarkar/Desktop/Arnav/IIIT/DSP/Excercize_3/Feedback.csv")
df.head(16)

,Timestamp,Level of effort instructor put into the course [Level of effort instructor put into the course],Contribution of course to your skill/knowledge [Contribution of course to your skill/knowledge],Skill and responsiveness of the instructor [Instructor was an effective lecturer/demonstrator],Skill and responsiveness of the instructor [Presentations were clear and organized],Skill and responsiveness of the instructor [Instructor stimulated student interest],Skill and responsiveness of the instructor [Instructor effectively used time during class periods],Skill and responsiveness of the instructor [Instructor was available and helpful],Skill and responsiveness of the instructor [Grading was prompt and had useful feedback],Course content [Learning objectives were clear],Course content [Course content was organized and well planned],Course content [Course workload was appropriate],Course content [Course organized to allow all students to participate fully],How would you rate the overall course?,What aspects of this course were most useful or valuable?,How would you improve this course?,Any other comments
0,7/17/2025 15:43:57,Very good,Satisfactory,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,NaN,NaN,NaN
1,7/17/2025 15:44:31,Very good,Satisfactory,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Most usful,By conducting more hands on session,Good faculty
2,7/17/2025 15:44:47,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Good,Machine learning techniques,NaN,NaN
3,7/17/2025 15:45:22,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,came to know about data science from scratch,with more hands-on,overall satisfied with the content delivery
4,7/17/2025 15:45:25,Very good,Very good,Agree,Agree,Agree,Agree,Strongly agree,Strongly agree,Agree,Agree,Agree,Agree,Good,Machine Learning,NaN,NaN
5,7/17/2025 15:45:51,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Data Science and Machine learning types,Through more Practical Applications,Very Interesting Subject learned a lot and gai...
6,7/17/2025 15:45:57,Excellent,Very good,Strongly agree,Agree,Strongly agree,Agree,Strongly agree,Strongly agree,Agree,Neutral,Agree,Agree,Good,NaN,more examples,NaN
7,7/17/2025 15:46:15,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Learning ML,By learning ML,NIL
8,7/17/2025 15:46:58,Excellent,Very good,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,"Machine learning, Data visualization using Tab...",May be few practical case studies if referred ...,"You are just an awesome teacher Wahid sir, Tha..."
9,7/17/2025 15:47:38,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Linear Regression and knowing the basics of Da...,NaN,NaN
10,7/17/2025 15:47:54,Excellent,Very good,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Agree,Agree,Agree,Very Good,data science we got some insight,more practical and hands on session,NaN
11,7/17/2025 15:48:45,Excellent,Excellent,Strongly agree,Strongly agree,Agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Agree,Strongly agree,Strongly agree,Very Good,along with course Data science and Machine lea...,The course was excellent it will get more usef...,Excellent Course Structure
12,7/17/2025 15:49:08,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,The most valuable aspect of this course was th...,The course provided a solid foundation in data...,The over all classes and labs were excellent a...
13,7/17/2025 15:50:13,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Agree,Neutral,Agree,Agree,Very Good,-,-,-
14,7/17/2025 15:51:50,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Weka Tool,More practical experiments,Thank You
15,7/17/2025 15:52:38,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Data science and machine learning,will improve this course by regular practice,no

In [ ]:
# Display the column names, number of rows
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 17 columns):
 #   Column                                                                                              Non-Null Count  Dtype
---  ------                                                                                              --------------  -----
 0   Timestamp                                                                                           34 non-null     object
 1   Level of effort instructor put into the course [Level of effort instructor put into the course]     34 non-null     object
 2   Contribution of course to your skill/knowledge [Contribution of course to your skill/knowledge]     34 non-null     object
 3   Skill and responsiveness of the instructor [Instructor was an effective lecturer/demonstrator]      34 non-null     object
 4   Skill and responsiveness of the instructor [Presentations were clear and organized]                 34 non-null     object
 5   Skill and responsiveness of the instructor [Instructor stimulated student interest]                 34 non-null     object
 6   Skill and responsiveness of the instructor [Instructor effectively used time during class periods]  34 non-null     object
 7   Skill and responsiveness of the instructor [Instructor was available and helpful]                   34 non-null     object
 8   Skill and responsiveness of the instructor [Grading was prompt and had useful feedback]             34 non-null     object
 9   Course content [Learning objectives were clear]                                                     34 non-null     object
 10  Course content [Course content was organized and well planned]                                      34 non-null     object
 11  Course content [Course workload was appropriate]                                                    34 non-null     object
 12  Course content [Course organized to allow all students to participate fully]                        34 non-null     object
 13  How would you rate the overall course?                                                              34 non-null     object
 14  What aspects of this course were most useful or valuable?                                           29 non-null     object
 15  How would you improve this course?                                                                  23 non-null     object
 16  Any other comments                                                                                  20 non-null     object
dtypes: object(17)
memory usage: 4.6+ KB

In [5]:
# Display all the missing values data
df.isnull()

,Timestamp,Level of effort instructor put into the course [Level of effort instructor put into the course],Contribution of course to your skill/knowledge [Contribution of course to your skill/knowledge],Skill and responsiveness of the instructor [Instructor was an effective lecturer/demonstrator],Skill and responsiveness of the instructor [Presentations were clear and organized],Skill and responsiveness of the instructor [Instructor stimulated student interest],Skill and responsiveness of the instructor [Instructor effectively used time during class periods],Skill and responsiveness of the instructor [Instructor was available and helpful],Skill and responsiveness of the instructor [Grading was prompt and had useful feedback],Course content [Learning objectives were clear],Course content [Course content was organized and well planned],Course content [Course workload was appropriate],Course content [Course organized to allow all students to participate fully],How would you rate the overall course?,What aspects of this course were most useful or valuable?,How would you improve this course?,Any other comments
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [6]:
# Now display all the columns which have missing values
df.columns[df.isnull().any()]

Index(['What aspects of this course were most useful or valuable?',
       'How would you improve this course?', 'Any other comments'],
      dtype='object')

In [7]:
# Display all the rows which have missing values
df[df.isnull().any(axis=1)]

,Timestamp,Level of effort instructor put into the course [Level of effort instructor put into the course],Contribution of course to your skill/knowledge [Contribution of course to your skill/knowledge],Skill and responsiveness of the instructor [Instructor was an effective lecturer/demonstrator],Skill and responsiveness of the instructor [Presentations were clear and organized],Skill and responsiveness of the instructor [Instructor stimulated student interest],Skill and responsiveness of the instructor [Instructor effectively used time during class periods],Skill and responsiveness of the instructor [Instructor was available and helpful],Skill and responsiveness of the instructor [Grading was prompt and had useful feedback],Course content [Learning objectives were clear],Course content [Course content was organized and well planned],Course content [Course workload was appropriate],Course content [Course organized to allow all students to participate fully],How would you rate the overall course?,What aspects of this course were most useful or valuable?,How would you improve this course?,Any other comments
0,7/17/2025 15:43:57,Very good,Satisfactory,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,NaN,NaN,NaN
2,7/17/2025 15:44:47,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Good,Machine learning techniques,NaN,NaN
4,7/17/2025 15:45:25,Very good,Very good,Agree,Agree,Agree,Agree,Strongly agree,Strongly agree,Agree,Agree,Agree,Agree,Good,Machine Learning,NaN,NaN
6,7/17/2025 15:45:57,Excellent,Very good,Strongly agree,Agree,Strongly agree,Agree,Strongly agree,Strongly agree,Agree,Neutral,Agree,Agree,Good,NaN,more examples,NaN
9,7/17/2025 15:47:38,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Linear Regression and knowing the basics of Da...,NaN,NaN
10,7/17/2025 15:47:54,Excellent,Very good,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Agree,Agree,Agree,Very Good,data science we got some insight,more practical and hands on session,NaN
19,7/17/2025 15:58:21,Excellent,Very good,Strongly agree,Strongly agree,Agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Agree,Agree,Strongly agree,Very Good,Very informative for non CS faculty,NaN,NaN
20,7/17/2025 15:59:25,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,Strongly agree,Agree,Very Good,Hands on experience on software,NaN,NaN
21,7/17/2025 16:00:03,Fair,Satisfactory,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Good,NaN,NaN,NaN
23,7/17/2025 16:00:43,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,NaN,NaN,NaN
24,7/17/2025 16:24:52,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,most valuable and useful,NaN,no
27,7/17/2025 16:28:15,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,NaN,NaN,NaN
31,7/18/2025 19:17:57,Very good,Very good,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Very Good,Weka tool,More physical classes are to conducted for bet...,NaN
32,7/21/2025 9:38:09,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,Basics of data science,NaN,NaN
33,7/28/2025 19:01:44,Excellent,Excellent,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Very Good,It is useful for our research work,By more practicing,NaN

In [8]:
# Find how many total responses were collected.
df.shape[0]

34

In [ ]:
import pandas as pd

# Expanded mapping
rating_map = {
    "Excellent": 5,
    "Very Good": 4,
    "Good": 3,
    "Average": 2,
    "Poor": 1,
    "Strongly agree": 5,
    "Agree": 4,
    "Neutral": 3,
    "Disagree": 2,
    "Strongly disagree": 1,
    "Satisfactory": 3
}

# Load CSV
df = pd.read_csv("feedback.csv")

# Columns to ignore (non-rating text)
exclude_cols = [
    "Timestamp",
    "What aspects of this course were most useful or valuable?",
    "How would you improve this course?",
    "Any other comments"
]

# Rating columns = everything except excluded
rating_columns = [col for col in df.columns if col not in exclude_cols]

# Apply mapping
for col in rating_columns:
    df[col] = df[col].map(rating_map)

#  Filter rows where *any rating column* >= 4
filtered_df = df[df[rating_columns].ge(4).any(axis=1)]

# Save filtered feedback
filtered_df.to_csv("filtered_feedback.csv", index=False)

# Calculate averages
overall_avg = df[rating_columns].mean().mean()
per_column_avg = df[rating_columns].mean()

print("Filtered feedback saved to filtered_feedback.csv")
print(f"Overall Average Rating: {overall_avg:.2f}")
print("\nAverage per Question:\n", per_column_avg)

Filtered feedback saved to filtered_feedback.csv
Overall Average Rating: 4.70

Average per Question:
 Level of effort instructor put into the course [Level of effort instructor put into the course]       5.000000
Contribution of course to your skill/knowledge [Contribution of course to your skill/knowledge]       4.760000
Skill and responsiveness of the instructor [Instructor was an effective lecturer/demonstrator]        4.852941
Skill and responsiveness of the instructor [Presentations were clear and organized]                   4.794118
Skill and responsiveness of the instructor [Instructor stimulated student interest]                   4.764706
Skill and responsiveness of the instructor [Instructor effectively used time during class periods]    4.823529
Skill and responsiveness of the instructor [Instructor was available and helpful]                     4.764706
Skill and responsiveness of the instructor [Grading was prompt and had useful feedback]               4.735294
Course content [Learning objectives were clear]                                                       4.764706
Course content [Course content was organized and well planned]                                        4.558824
Course content [Course workload was appropriate]                                                      4.705882
Course content [Course organized to allow all students to participate fully]                          4.705882
How would you rate the overall course?                                                                3.852941
dtype: float64